In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [15]:
def forward_backward(indep_X,dep_Y,n,estimator):
        test = SequentialFeatureSelector(estimator=estimator,n_features_to_select=n,direction="forward")
        fit1= test.fit(indep_X,dep_Y)
        # summarize scores       
        forw_back = fit1.transform(indep_X)
        return forw_back

In [16]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test

In [17]:
def r2_prediction(estimator,X_test,y_test):
     y_pred = estimator.predict(X_test)
     from sklearn.metrics import r2_score
     r2=r2_score(y_test,y_pred)
     return r2

In [37]:
def Linear(X_train,y_train,X_test):
    from sklearn.linear_model import LinearRegression
    estimator = LinearRegression()
    estimator.fit(X_train, y_train)
    r2=r2_prediction(estimator,X_test,y_test)
    return  r2

In [38]:
def selectk_regression(acclin): 
    
    dataframe=pd.DataFrame(index=['selected_feature'],columns=['Linear'])

    for number,idex in enumerate(dataframe.index):# enumerate will provide (Index,Value/Element ex:-Apple,Orange,Banana. It will start 0,1,2) for number it will take first 0 and idex will have apple
        dataframe.loc[idex,'Linear']=acclin[number]       
    return dataframe

In [39]:
dataset1=pd.read_csv("prep.csv",index_col=None)
df2=dataset1

In [40]:
df2= pd.get_dummies(df2, drop_first=True)

In [41]:
indep_X = df2.drop("classification_yes", axis=1)

In [42]:
# Convert to integers (0/1)
dep_Y = df2["classification_yes"].astype(int)

In [43]:
from sklearn.linear_model import LinearRegression
estimator=LinearRegression()

In [81]:
for_back=forward_backward(indep_X,dep_Y,9,estimator)

In [82]:
acclin=[]
X_train, X_test, y_train, y_test=split_scalar(for_back,dep_Y)
for i in for_back:   
    r2_lin=Linear(X_train,y_train,X_test)
    acclin.append(r2_lin)
result=selectk_regression(acclin)

In [74]:
#result 4

                    Linear
selected_feature  0.667361

In [64]:
#result 5

                    Linear
selected_feature  0.692984

In [83]:
#result 9

                    Linear
selected_feature  0.712455